#!/bin/sh

if [ "`uname`" = "Darwin" ]; then
  alias ls='ls -G'
fi

if [ "`uname`" = "Linux" ]; then
  alias ls='ls --color'
fi

alias quit='tmux kill-session'

if [ -s "$HOME/.aliases.local" ]; then
  . ~/.aliases.local
fi
